server:
  port: 8085
spring:
  application:
    name: product-service-api
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5435/ecommerce}
    username: ${DATSOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
security:
  roles:
    admin-access: ADMIN
    user-access: USER
    all-access: ADMIN,USER

logging:
  level:
    org:
      springframework.web: DEBUG
      apache.catalina: DEBUG
      apache.coyote: DEBUG